"""Live browser editor for the physical factory-floor projection."""

VISUAL_EDITOR_HTML = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,">
<title>Nero Floor Light Studio</title>
<style>
:root{color-scheme:dark;--void:#040706;--panel:#09100d;--panel2:#0d1712;--line:#21342a;--ink:#f4fff8;--muted:#8ca096;--mint:#8cffd0;--amber:#ffd34d;--cyan:#65e8ff;--danger:#ff655f}
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;background:var(--void);color:var(--ink)}body{font-family:"Arial Narrow","DejaVu Sans Condensed",sans-serif;overflow:hidden}
button,input{font:inherit}.shell{height:100vh;display:grid;grid-template-rows:64px minmax(0,1fr)}
header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:28px;padding:0 22px;border-bottom:1px solid var(--line);background:#060a08}
.brand{display:flex;align-items:baseline;gap:13px}.brand strong{font-size:21px;letter-spacing:.2em}.brand span,.eyebrow,.meta{font:600 10px "Liberation Mono",monospace;letter-spacing:.15em;text-transform:uppercase;color:var(--muted)}
.beam{height:1px;background:linear-gradient(90deg,var(--mint),#315044 35%,#315044 65%,var(--amber));position:relative}.beam:before,.beam:after{content:"";position:absolute;top:-3px;width:7px;height:7px;border-radius:50%}.beam:before{left:0;background:var(--mint);box-shadow:0 0 12px var(--mint)}.beam:after{right:0;background:var(--amber);box-shadow:0 0 12px var(--amber)}
.live{display:flex;align-items:center;gap:9px;font:700 10px "Liberation Mono",monospace;letter-spacing:.14em;color:var(--mint)}.live i{width:7px;height:7px;border-radius:50%;background:var(--mint);box-shadow:0 0 13px var(--mint)}.live.saving{color:var(--amber)}.live.saving i{background:var(--amber);box-shadow:0 0 13px var(--amber)}
main{min-height:0;display:grid;grid-template-columns:minmax(640px,1fr) 390px}.preview{min-height:0;padding:18px;display:grid;grid-template-rows:38px minmax(0,1fr) 45px;border-right:1px solid var(--line)}
.preview-head,.preview-foot{display:flex;align-items:center;justify-content:space-between}.preview-head strong{font-size:14px;letter-spacing:.08em}.preview-foot{font:10px "Liberation Mono",monospace;color:var(--muted);letter-spacing:.08em}.preview-foot b{color:var(--mint);font-weight:500}
.stage{min-height:0;position:relative;border:1px solid #2a4436;background:#000;clip-path:polygon(0 0,calc(100% - 15px) 0,100% 15px,100% 100%,15px 100%,0 calc(100% - 15px));overflow:hidden}.stage canvas{width:100%;height:100%;display:block}.stage:after{content:"PROJECTOR OUTPUT SIMULATION";position:absolute;right:14px;top:12px;font:9px "Liberation Mono",monospace;letter-spacing:.14em;color:#8cffd099}
.inspector{min-height:0;overflow:auto;background:var(--panel);padding:18px 20px 28px}.section{padding:0 0 20px;margin:0 0 20px;border-bottom:1px solid var(--line)}.section:last-child{border:0}.section h2{margin:7px 0 14px;font-size:18px;letter-spacing:.04em}.section p{margin:0;color:var(--muted);font-size:13px;line-height:1.5}
.mode-switch{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mode{min-height:72px;text-align:left;padding:11px;border:1px solid #2d4438;background:#0a130f;color:var(--muted);cursor:pointer}.mode strong{display:block;color:var(--ink);font-size:14px;margin-bottom:5px}.mode span{font:9px "Liberation Mono",monospace;letter-spacing:.07em;text-transform:uppercase}.mode.active{border-color:var(--mint);background:#10241b;color:var(--mint);box-shadow:inset 0 -3px var(--mint)}.mode:focus-visible,.preset:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}
.presets{display:grid;gap:7px}.preset{display:grid;grid-template-columns:76px 1fr;align-items:center;gap:11px;padding:8px;border:1px solid #283d33;background:#08100c;color:var(--muted);cursor:pointer;text-align:left}.preset canvas{width:76px;height:45px;background:#000;border:1px solid #1e3028}.preset strong{display:block;color:var(--ink);font-size:13px;margin-bottom:4px}.preset span{font-size:11px}.preset.active{border-color:var(--mint);background:#0d1d16}.preset.recommended strong:after{content:"DEFAULT";margin-left:8px;color:var(--mint);font:8px "Liberation Mono",monospace;letter-spacing:.1em}
.control{display:grid;grid-template-columns:1fr auto;align-items:center;gap:7px;margin:0 0 14px}.control label{font-size:12px;color:#cfe0d7}.control output{font:10px "Liberation Mono",monospace;color:var(--mint)}.control input[type=range]{grid-column:1/-1;width:100%;accent-color:var(--mint)}
.colors{display:grid;grid-template-columns:1fr 1fr;gap:8px}.color{display:grid;grid-template-columns:34px 1fr;align-items:center;gap:8px;padding:8px;border:1px solid var(--line);background:#070d0a}.color input{width:34px;height:32px;border:0;background:none;padding:0}.color span{font-size:11px;color:var(--muted)}
.coordinate{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--line);border:1px solid var(--line)}.readout{background:#08100c;padding:10px}.readout small{display:block;font:8px "Liberation Mono",monospace;letter-spacing:.12em;color:var(--muted);text-transform:uppercase}.readout b{display:block;margin-top:7px;font:16px "Liberation Mono",monospace;color:var(--cyan)}
@media(max-width:1050px){body{overflow:auto}.shell{height:auto;min-height:100vh}main{grid-template-columns:1fr}.preview{height:70vh;border-right:0;border-bottom:1px solid var(--line)}.inspector{overflow:visible}.beam{display:none}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style></head>
<body><div class="shell">
<header><div class="brand"><strong>NERO</strong><span>floor light studio</span></div><div class="beam"></div><div id="live" class="live"><i></i><span>live to HDMI</span></div></header>
<main>
  <section class="preview"><div class="preview-head"><strong>Factory floor projection</strong><span class="meta">black carpet · low-lumen compensation</span></div><div class="stage"><canvas id="stage" width="1280" height="720"></canvas></div><div class="preview-foot"><span><b>Mint</b> planned intent · <b style="color:var(--amber)">Amber</b> pickup target</span><span id="modeLabel">Mission / Intent field</span></div></section>
  <aside class="inspector">
    <section class="section"><span class="eyebrow">Display mode</span><h2>What the floor communicates</h2><div class="mode-switch"><button class="mode" data-mode="engineering"><strong>Engineering</strong><span>XY · footprint · chevrons</span></button><button class="mode" data-mode="mission"><strong>Mission</strong><span>intent · pickup target</span></button></div></section>
    <section class="section"><span class="eyebrow">Mission treatment</span><h2>Choose the light behavior</h2><div class="presets">
      <button class="preset recommended" data-preset="intent_field"><canvas width="152" height="90"></canvas><span><strong>Intent field</strong>A tapered, glowing approach that stops before the target.</span></button>
      <button class="preset" data-preset="beacon_trail"><canvas width="152" height="90"></canvas><span><strong>Beacon trail</strong>Separated droplets make motion legible on dark carpet.</span></button>
      <button class="preset" data-preset="safety_corridor"><canvas width="152" height="90"></canvas><span><strong>Safety corridor</strong>Bright rails reserve a clear factory travel zone.</span></button>
    </div></section>
    <section class="section"><span class="eyebrow">Optical tuning</span><h2>Compensate for the room</h2>
      <div class="control"><label for="route_width">Field width</label><output id="route_width_v"></output><input id="route_width" type="range" min="0.025" max="0.14" step="0.005"></div>
      <div class="control"><label for="goal_gap">Target breathing room</label><output id="goal_gap_v"></output><input id="goal_gap" type="range" min="0.02" max="0.22" step="0.005"></div>
      <div class="control"><label for="target_radius">Target halo</label><output id="target_radius_v"></output><input id="target_radius" type="range" min="0.03" max="0.14" step="0.005"></div>
      <div class="control"><label for="glow_strength">Glow output</label><output id="glow_strength_v"></output><input id="glow_strength" type="range" min="0.1" max="1" step="0.05"></div>
      <div class="control"><label for="animation_speed">Flow speed</label><output id="animation_speed_v"></output><input id="animation_speed" type="range" min="0.1" max="2.5" step="0.1"></div>
      <div class="control"><label for="grid_intensity">Mission grid</label><output id="grid_intensity_v"></output><input id="grid_intensity" type="range" min="0.15" max="1" step="0.05"></div>
      <div class="colors"><label class="color"><input id="route_color" type="color"><span>Intent light</span></label><label class="color"><input id="target_color" type="color"><span>Pickup target</span></label></div>
    </section>
    <section class="section"><span class="eyebrow">Live room frame</span><h2>Robot → target</h2><div class="coordinate"><div class="readout"><small>Robot XY</small><b id="robotXY">—</b></div><div class="readout"><small>Target XY</small><b id="targetXY">—</b></div></div></section>
  </aside>
</main></div>
<script>
const $=selector=>document.querySelector(selector),stage=$('#stage'),ctx=stage.getContext('2d');
const defaults={mode:'engineering',preset:'intent_field',route_color:'#8CFFD0',target_color:'#FFD34D',route_width:.07,goal_gap:.085,target_radius:.065,glow_strength:.9,animation_speed:.8,grid_intensity:.55};
let visual={...defaults},ready=false,sendTimer=0,lastFrame=0;
const ranges=['route_width','goal_gap','target_radius','glow_strength','animation_speed','grid_intensity'];
function hexAlpha(hex,alpha){const value=parseInt(hex.slice(1),16);return `rgba(${value>>16},${value>>8&255},${value&255},${alpha})`}
function point(t){const u=1-t;return{x:u*u*235+2*u*t*575+t*t*1015,y:u*u*535+2*u*t*430+t*t*205}}
function tangent(t){const a=point(Math.max(0,t-.002)),b=point(Math.min(1,t+.002)),dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;return{x:dx/l,y:dy/l}}
function perspectiveGrid(){ctx.save();ctx.strokeStyle=hexAlpha(visual.route_color,visual.mode==='mission'?.16*visual.grid_intensity:.34);ctx.lineWidth=2;const q=[[85,70],[1195,70],[1245,655],[35,655]];for(let i=0;i<=16;i++){let t=i/16;ctx.beginPath();ctx.moveTo(q[0][0]+(q[1][0]-q[0][0])*t,q[0][1]);ctx.lineTo(q[3][0]+(q[2][0]-q[3][0])*t,q[3][1]);ctx.stroke()}for(let i=0;i<=10;i++){let t=i/10;ctx.beginPath();ctx.moveTo(q[0][0]+(q[3][0]-q[0][0])*t,q[0][1]+(q[3][1]-q[0][1])*t);ctx.lineTo(q[1][0]+(q[2][0]-q[1][0])*t,q[1][1]+(q[2][1]-q[1][1])*t);ctx.stroke()}ctx.restore()}
function target(t){const p=point(t),r=visual.target_radius*520*(1+.04*Math.sin(performance.now()/500));ctx.save();ctx.shadowColor=visual.target_color;ctx.shadowBlur=30*visual.glow_strength;ctx.strokeStyle=visual.target_color;ctx.lineWidth=8;ctx.beginPath();ctx.arc(p.x,p.y,r*1.35,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,r,.15,Math.PI*1.85);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,8,0,7);ctx.fill();ctx.shadowBlur=0;ctx.font='700 20px Arial Narrow';ctx.letterSpacing='3px';ctx.fillText('TARGET',p.x+r*1.55,p.y-r*1.2);ctx.restore()}
function dropAt(t,scale=1){const p=point(t),d=tangent(t),n={x:-d.y,y:d.x},s=22*scale;ctx.beginPath();ctx.moveTo(p.x+d.x*s*1.2,p.y+d.y*s*1.2);ctx.lineTo(p.x+n.x*s*.48,p.y+n.y*s*.48);ctx.lineTo(p.x-d.x*s,p.y-d.y*s);ctx.lineTo(p.x-n.x*s*.48,p.y-n.y*s*.48);ctx.closePath();ctx.fill()}
function mission(now){const end=.84,steps=80,width=visual.route_width*620;ctx.save();if(visual.preset==='intent_field'){ctx.beginPath();for(let i=0;i<=steps;i++){let t=end*i/steps,p=point(t),d=tangent(t),n={x:-d.y,y:d.x},w=width*(.96-.82*Math.pow(i/steps,1.35));i?ctx.lineTo(p.x+n.x*w,p.y+n.y*w):ctx.moveTo(p.x+n.x*w,p.y+n.y*w)}for(let i=steps;i>=0;i--){let t=end*i/steps,p=point(t),d=tangent(t),n={x:-d.y,y:d.x},w=width*(.96-.82*Math.pow(i/steps,1.35));ctx.lineTo(p.x-n.x*w,p.y-n.y*w)}ctx.closePath();ctx.shadowColor=visual.route_color;ctx.shadowBlur=45*visual.glow_strength;ctx.fillStyle=hexAlpha(visual.route_color,.38*visual.glow_strength);ctx.fill();ctx.shadowBlur=15;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}
if(visual.preset==='safety_corridor'){for(const side of [-1,1]){ctx.beginPath();for(let i=0;i<=steps;i++){let t=end*i/steps,p=point(t),d=tangent(t),n={x:-d.y,y:d.x};i?ctx.lineTo(p.x+n.x*width*side,p.y+n.y*width*side):ctx.moveTo(p.x+n.x*width*side,p.y+n.y*width*side)}ctx.shadowColor=visual.route_color;ctx.shadowBlur=24;ctx.strokeStyle=visual.route_color;ctx.lineWidth=11;ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke()}}
ctx.fillStyle=visual.route_color;ctx.shadowColor=visual.route_color;ctx.shadowBlur=26*visual.glow_strength;const count=visual.preset==='beacon_trail'?8:4;for(let i=0;i<count;i++){let t=((now/5200*visual.animation_speed+i/count)%1)*end;dropAt(t,visual.preset==='beacon_trail'?1.25:.75)}ctx.restore();target(1)}
function engineering(now){ctx.save();ctx.strokeStyle='#52dfff';ctx.shadowColor='#52dfff';ctx.shadowBlur=18;ctx.lineWidth=22;ctx.beginPath();let p=point(0);ctx.moveTo(p.x,p.y);for(let i=1;i<=60;i++){p=point(i/60);ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';for(let i=0;i<7;i++)dropAt(((now/4800+i/7)%1),.65);const start=point(0);ctx.strokeStyle='#ff9f25';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(start.x+145,start.y);ctx.stroke();ctx.fillStyle='#fff';ctx.font='700 17px Arial Narrow';ctx.fillText('+X / FORWARD',start.x+152,start.y+6);ctx.strokeStyle='#65e8ff';ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(start.x,start.y-110);ctx.stroke();ctx.fillText('+Y',start.x+8,start.y-118);ctx.restore();target(1)}
function draw(now){ctx.fillStyle='#000';ctx.fillRect(0,0,stage.width,stage.height);perspectiveGrid();visual.mode==='mission'?mission(now):engineering(now);requestAnimationFrame(draw)}
function paintMini(button,preset){const c=button.querySelector('canvas'),g=c.getContext('2d');g.fillStyle='#000';g.fillRect(0,0,c.width,c.height);g.strokeStyle=hexAlpha(visual.route_color,.23);g.lineWidth=1;for(let y=12;y<90;y+=18){g.beginPath();g.moveTo(0,y);g.lineTo(152,y);g.stroke()}g.strokeStyle=visual.target_color;g.lineWidth=3;g.beginPath();g.arc(130,24,12,0,7);g.stroke();if(preset==='safety_corridor'){g.strokeStyle=visual.route_color;g.lineWidth=4;for(const o of [-8,8]){g.beginPath();g.moveTo(18,70+o);g.quadraticCurveTo(75,55+o,112,31+o);g.stroke()}}else{g.fillStyle=visual.route_color;const count=preset==='beacon_trail'?6:3;for(let i=0;i<count;i++){g.beginPath();g.ellipse(20+i*17,67-i*7,preset==='beacon_trail'?7:12,4,-.35,0,7);g.fill()}}}
function refresh(){document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===visual.mode));document.querySelectorAll('.preset').forEach(b=>{b.classList.toggle('active',b.dataset.preset===visual.preset);paintMini(b,b.dataset.preset)});ranges.forEach(id=>{const input=$('#'+id);input.value=visual[id];$('#'+id+'_v').textContent=id.includes('speed')?`${Number(visual[id]).toFixed(1)}×`:`${Math.round(visual[id]*100)}%`});$('#route_color').value=visual.route_color;$('#target_color').value=visual.target_color;$('#modeLabel').textContent=visual.mode==='mission'?`Mission / ${visual.preset.replace('_',' ')}`:'Engineering / XY frame'}
async function send(){if(!ready)return;const live=$('#live');live.classList.add('saving');live.querySelector('span').textContent='applying';try{const r=await fetch('/api/visualization',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(visual)});if(!r.ok)throw new Error(await r.text());visual=await r.json();refresh();live.querySelector('span').textContent='live to HDMI'}catch(e){live.querySelector('span').textContent='update failed'}finally{live.classList.remove('saving')}}
function schedule(){clearTimeout(sendTimer);sendTimer=setTimeout(send,55)}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{visual.mode=b.dataset.mode;refresh();schedule()});document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{visual.mode='mission';visual.preset=b.dataset.preset;refresh();schedule()});ranges.forEach(id=>$('#'+id).oninput=e=>{visual[id]=Number(e.target.value);refresh();schedule()});for(const id of ['route_color','target_color'])$('#'+id).oninput=e=>{visual[id]=e.target.value.toUpperCase();refresh();schedule()};
document.onkeydown=e=>{if(e.key==='1')document.querySelector('[data-mode="engineering"]').click();if(e.key==='2')document.querySelector('[data-mode="mission"]').click()};
async function navigation(){try{const d=await(await fetch('/api/navigation/state',{cache:'no-store'})).json(),r=d.robot_pose,g=d.goal_pose;$('#robotXY').textContent=r?`${r.x.toFixed(2)} / ${r.y.toFixed(2)}`:'—';$('#targetXY').textContent=g?`${g.x.toFixed(2)} / ${g.y.toFixed(2)}`:'—'}catch(_){}setTimeout(navigation,400)}
fetch('/api/visualization').then(r=>r.json()).then(d=>{visual={...defaults,...d};ready=true;refresh()}).catch(()=>{ready=true;refresh()});refresh();navigation();requestAnimationFrame(draw);
</script></body></html>"""
